# Generated by Django 5.0.4 on 2024-04-23 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/images')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagees', to='store.product')),
            ],
        ),
    ]
